# Generated by Django 5.0.6 on 2024-06-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_emplo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=14)),
                ('photo', models.ImageField(upload_to='uploded images/')),
            ],
        ),
        migrations.AlterField(
            model_name='emplo',
            name='mobile',
            field=models.IntegerField(verbose_name='mobile number'),
        ),
    ]
